### ISSUE TITLE
调用服务时，报这个错误

### ISSUE THREAD

**Issue by Seifon** [hasscc/hass-edge-tts#17]
Logger: homeassistant.helpers.script.websocket_api_script
Source: .local/lib/python3.10/site-packages/edgeTTS/__init__.py:129
First occurred: 00:21:22 (2 occurrences)
Last logged: 00:21:22

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: can only concatenate str (not "float") to str
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/lib/python3.10/site-packages/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task

**Comment by rany2** [comment]
Could you show the full traceback?

**Comment by rany2** [comment]
>  Source: .local/lib/python3.10/site-packages/edgeTTS/init.py:129

This version is too old, you need to update edge-tts.
