### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by Murianwind** [hasscc/hass-edge-tts#28]
Home Assistant 2023.1.0
Supervisor 2022.12.1
Operating System 9.4
Frontend 버전: 20230104.0 - latest

=====
이 오류는 사용자 통합구성요소에서 발생했습니다.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/edge_tts/tts.py:407
Integration: edge_tts (documentation, issues)
First occurred: 20:42:04 (2 occurrences)
Last logged: 20:42:13

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: expected string or bytes-like object
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 217, in async_say_handle
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 644, in async_play_media
    sourced_media = await media_source.async_resolve_media(
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 155, in async_resolve_media
    return await item.async_resolve()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 83, in async_resolve
    return await self.async_media_source().async_resolve_media(self)
  File "/usr/src/homeassistant/homeassistant/components/tts/media_source.py", line 117, in async_resolve_media
    url = await manager.async_get_url_path(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 426, in async_get_url_path
    filename = await self._async_get_tts_audio(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 492, in _async_get_tts_audio
    extension, data = await provider.async_get_tts_audio(message, language, options)
  File "/config/custom_components/edge_tts/tts.py", line 407, in async_get_tts_audio
    tts = EdgeCommunicate(
  File "/usr/local/lib/python3.10/site-packages/edge_tts/communicate.py", line 269, in __init__
    if re.match(r"^[+-]?\d+%$", volume) is None:
  File "/usr/local/lib/python3.10/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

======
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/edge_tts/tts.py:407
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:42:04 (2 occurrences)
Last logged: 20:42:13

[281472595277856] Error handling message: Unknown error (unknown_error) from 192.168.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
[281472677033776] Error handling message: Unknown error (unknown_error) from 192.168.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 646, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 217, in async_say_handle
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 644, in async_play_media
    sourced_media = await media_source.async_resolve_media(
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 155, in async_resolve_media
    return await item.async_resolve()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 83, in async_resolve
    return await self.async_media_source().async_resolve_media(self)
  File "/usr/src/homeassistant/homeassistant/components/tts/media_source.py", line 117, in async_resolve_media
    url = await manager.async_get_url_path(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 426, in async_get_url_path
    filename = await self._async_get_tts_audio(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 492, in _async_get_tts_audio
    extension, data = await provider.async_get_tts_audio(message, language, options)
  File "/config/custom_components/edge_tts/tts.py", line 407, in async_get_tts_audio
    tts = EdgeCommunicate(
  File "/usr/local/lib/python3.10/site-packages/edge_tts/communicate.py", line 269, in __init__
    if re.match(r"^[+-]?\d+%$", volume) is None:
  File "/usr/local/lib/python3.10/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

====
And my config

tts:
  - platform: edge_tts
    language: ko-KR-SunHiNeural
    volume: 200.0

**Comment by rany2** [comment]
Must be `volume=+200%`

**Comment by Murianwind** [comment]
> Must be `volume: +200%`

Thanks a lot!!!

**Comment by rany2** [comment]
Reopening, error needs to be clearer
