### ISSUE TITLE
Detected blocking call

### ISSUE THREAD

**Issue by demey** [hasscc/hass-edge-tts#49]
Home Assistant
Core 2024.7.3
Supervisor 2024.06.2
Operating System 12.4 

`WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/root/.netrc',) inside the event loop by custom integration 'edge_tts' at custom_components/edge_tts/tts.py, line 408: async for chunk in tts.stream(): (offender: /usr/local/lib/python3.12/netrc.py, line 74: with open(file, encoding="utf-8") as fp:), please create a bug report at https://github.com/hasscc/hass-edge-tts/issues`

For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 727, in get_tts_data
    extension, data = await engine_instance.async_get_tts_audio(
  File "/config/custom_components/edge_tts/tts.py", line 408, in async_get_tts_audio
    async for chunk in tts.stream():

**Comment by demey** [comment]
Issue still exists.
HA version  2024.11.1

`2024-11-10 22:50:34.006 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f63cb67a350>, '/usr/local/lib/python3.12/site-packages/certifi/cacert.pem', None, None) inside the event loop by custom integration 'edge_tts' at custom_components/edge_tts/tts.py, line 408: async for chunk in tts.stream(): (offender: /usr/local/lib/python3.12/ssl.py, line 708: context.load_verify_locations(cafile, capath, cadata)), please create a bug report at https://github.com/hasscc/hass-edge-tts/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 767, in get_tts_data
    extension, data = await engine_instance.async_get_tts_audio(
  File "/config/custom_components/edge_tts/tts.py", line 408, in async_get_tts_audio
    async for chunk in tts.stream():

2024-11-10 22:50:34.014 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/root/.netrc',) inside the event loop by custom integration 'edge_tts' at custom_components/edge_tts/tts.py, line 408: async for chunk in tts.stream(): (offender: /usr/local/lib/python3.12/netrc.py, line 74: with open(file, encoding="utf-8") as fp:), please create a bug report at https://github.com/hasscc/hass-edge-tts/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 767, in get_tts_data
    extension, data = await engine_instance.async_get_tts_audio(
  File "/config/custom_components/edge_tts/tts.py", line 408, in async_get_tts_audio
    async for chunk in tts.stream():`

**Comment by demey** [comment]
I have changed line 408 in `/config/custom_components/edge_tts/tts.py`
from `async for chunk in tts.stream():` to `for chunk in tts.stream_sync():` and listed WARNINGs disappeared.
Integration works as expected.

**Comment by rany2** [comment]
I think the detection is a false positive. At least I can't find any blocking code for edge-tts that can cause this.

The reason the sync varient doesn't trigger itis likely because it starts a new event loop in a new thread which is likely not monitored by Home Assistant.

**Comment by XHyperDEVX** [comment]
@demey @rany2 
i have the same problem. i have already changed the code line as said by @demey, but now i get the following error:
> 2025-01-08 12:02:21.766 WARNING (MainThread) [zeroconf] Error with socket 26 (('fe80::921b:eff:fe45:3405', 5353, 0, 2))): [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 1266, in sendto
    self._sock.sendto(data, addr)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^

**Comment by rany2** [comment]
@XHyperDEVX That error is unrelated

**Comment by nareso** [comment]
Hi,

I am experiencing the same warning, and I would like to provide some clarification and suggestions for improvement.

**Warning log excerpt:**
Detected blocking call to load_verify_locations inside the event loop
by custom integration 'edge_tts' at custom_components/edge_tts/tts.py, line 140

- HA version: 2025.11.2
- Python: 3.13
- edge_tts integration: v0.7.3

**Background:**
The warning occurs because `context.load_verify_locations()` (used internally for SSL certificate verification) is executed inside the async event loop, which Home Assistant detects as a blocking call. While the actual TTS functionality works and the performance impact appears minimal, the asyncio best practices recommend avoiding synchronous blocking calls in the event loop.

**Possible improvements / proposals:**

1. **Run SSL certificate loading in an executor**
```python
loop = asyncio.get_running_loop()
await loop.run_in_executor(
    None,  # default executor
    lambda: context.load_verify_locations(cafile, capath, cadata)
)
```

- Prevents blocking the async event loop
- Minimal change in code, but requires modification inside tts.stream()

2. **Load certificates during initialization (before async streaming)**

```
# Example: in component setup()
context.load_verify_locations(cafile)
```

- Ensures the blocking call happens before entering async loop
- Simple and low-risk

3.**Operational approach**

- Continue current usage, as the warning does not affect functionality
- Optionally note it as a false positive in documentation

**Recommendation:**

- Option 2 (initialization loading) is a lightweight and safe improvement
- Option 1 (executor) is the best-practice approach if more strict async compliance is desired
- Option 3 is acceptable for users where performance impact is negligible

This report is mainly for tracking and potential improvement purposes.

Thanks for your attention and consideration.
